### ISSUE TITLE
package conflict 

### ISSUE THREAD

**Issue by cchd0001** [yuanzhiyuan/SOMENDER#1]
Hi， 

Thanks for developing this interesting package, I try to install it via pip but failed with below errors:

```
conda create -n mender1 python=3.11.8
pip install SOMENDER==1.1
```

![image](https://github.com/yuanzhiyuan/MENDER/assets/8720584/66ccf1f6-c600-47fa-b6c0-9cc88cd4ed8d)

**Comment by rrrzhan** [comment]
I also met this issue in python3.11. The version of numpy causes the conflict.
I solved the issue like this:
1. Download the source code.
2. Modify numpy>=1.22.4 in setup.py.
3. Run:
```
python setup.py install
```

**Comment by cchd0001** [comment]
> I also met this issue in python3.11. The version of numpy causes the conflict. I solved the issue like this:
> 
> 1. Download the source code.
> 2. Modify numpy>=1.22.4 in setup.py.
> 3. Run:
> 
> ```
> python setup.py install
> ```

Thanks.
